HW09 Struct Validator
AlexandrNikitin3776/OTUS2021Golang_Developer pull request #9
Opened 2022-09-25 21:30 UTC by AlexandrNikitin3776

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2022-11-01 03:01 UTC, dshemin requested changes

2022-11-01 03:01 UTC, dshemin commented on hw09_struct_validator/int_rules.go
> +		} else {
Здесь `else` можно опустить так, как если условие сработало, то мы завершим работу внутри этой функции. Можно переписать это в виде:
```
v, err := ParseIntRule(...)
if err != nil {
    return nil, err
}
result = append(...)
```

2022-11-01 03:01 UTC, dshemin commented on hw09_struct_validator/int_rules.go
> +		if intValue, err := strconv.Atoi(value); err != nil {
Тут тоже можно избежать использования `else`.

2022-11-01 03:01 UTC, dshemin commented on hw09_struct_validator/int_rules_test.go
> +				require.Error(t, err)
Круто что вы написали юнит тесты для этих функций, особенно что вы написали проверки для всех возможных сценариев. Но есть одна рекомендация, лучше всего проверять не только наличие ошибки, но и что это за ошибка через assert.EqualError или asser.ErrorIs.

2022-11-01 03:01 UTC, dshemin commented on hw09_struct_validator/string_rules.go
> +		if checkFunc, err := ParseStringRule(rule); err != nil {
Тут тоже модно избежать использования `else`

2022-11-01 03:01 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	result += fmt.Sprintln("errors while validation:")
Не самый эффективный способ собирание строки. Лучше использовать strings.Builder

2022-11-04 13:47 UTC, AlexandrNikitin3776 commented on hw09_struct_validator/int_rules.go
> +		} else {
Убрал else.
Коммит: https://github.com/AlexandrNikitin3776/OTUS2021Golang_Developer/pull/9/commits/5d06475186d3b06e458ffb5e274ba86905699cd5

2022-11-04 13:47 UTC, AlexandrNikitin3776 commented on hw09_struct_validator/int_rules.go
> +		if intValue, err := strconv.Atoi(value); err != nil {
Убрал else.
Коммит: https://github.com/AlexandrNikitin3776/OTUS2021Golang_Developer/pull/9/commits/5d06475186d3b06e458ffb5e274ba86905699cd5

2022-11-04 13:52 UTC, AlexandrNikitin3776 commented on hw09_struct_validator/int_rules_test.go
> +				require.Error(t, err)
Исправил require.Error на require.ErrorIs везде, кроме валидации регулярного выражения в string_rules_test.go::L#84. Там не получилось, метод Error определен в ошибке для указателя, а ErrorIs не хочет принимать указатель, поэтому использовал require.EqualError и проверил, что текст соответствует.

Коммит: https://github.com/AlexandrNikitin3776/OTUS2021Golang_Developer/pull/9/commits/f9544a73f073c9983d8a3ef726394ba827633208

2022-11-04 13:53 UTC, AlexandrNikitin3776 commented on hw09_struct_validator/validator.go
> +	result += fmt.Sprintln("errors while validation:")
Использовал strings.Builder

Коммит: https://github.com/AlexandrNikitin3776/OTUS2021Golang_Developer/pull/9/commits/0ec54cf6f93dabf8512f3f9232d7e432e69858a6

2022-11-04 13:56 UTC, AlexandrNikitin3776 commented on hw09_struct_validator/string_rules.go
> +		if checkFunc, err := ParseStringRule(rule); err != nil {
Убрал else.

Коммит: https://github.com/AlexandrNikitin3776/OTUS2021Golang_Developer/pull/9/commits/5d06475186d3b06e458ffb5e274ba86905699cd5

2022-11-05 02:43 UTC, dshemin approved these changes

2022-11-07 08:55 UTC, merged